// Bake a real settled bead pile ONCE, offline, into a static position table the
// app places instantly on load — so the jar looks identical every reload with no
// re-pour and no escapees. Pours beads into the EXACT BeadJar3D collider (same
// profile, inset, bead radius, damping) with real rapier physics, lets them
// settle, then writes src/components/pilePositions.js sorted bottom→top.
//
//   node scripts/bake-pile.mjs
import * as THREE from 'three'
import RAPIER from '@dimforge/rapier3d-compat'
import { writeFileSync } from 'fs'

const BEAD_R = 0.086        // MUST match BeadJar3D.BEAD_R
const N = 600               // measured capacity to the shoulder
const PROFILE = [
  [0.001, 0.0], [0.55, 0.0], [0.72, 0.05], [0.80, 0.16], [0.84, 0.45],
  [0.85, 0.95], [0.84, 1.28], [0.78, 1.50], [0.62, 1.66], [0.50, 1.74],
  [0.48, 1.82], [0.50, 1.90], [0.47, 1.93],
]

await RAPIER.init()
const world = new RAPIER.World({ x: 0, y: -14, z: 0 })

// jar interior collider — identical construction to BeadJar3D's Jar()
const inner = PROFILE.map(([r, y]) => new THREE.Vector2(Math.max(0.001, r - 0.06), Math.max(y, 0.05)))
const collGeo = new THREE.LatheGeometry(inner, 24)
const fixed = world.createRigidBody(RAPIER.RigidBodyDesc.fixed())
world.createCollider(
  RAPIER.ColliderDesc.trimesh(
    new Float32Array(collGeo.attributes.position.array),
    new Uint32Array(collGeo.index.array),
  ).setFriction(0.5).setRestitution(0.1),
  fixed,
)
world.createCollider(RAPIER.ColliderDesc.cuboid(3, 0.25, 3).setTranslation(0, -0.27, 0), fixed)

function idHash(i, salt) {
  let h = 2166136261 ^ salt
  const s = 'bead_' + i
  for (let k = 0; k < s.length; k++) { h ^= s.charCodeAt(k); h = Math.imul(h, 16777619) }
  return ((h >>> 0) % 10000) / 10000
}

const bodies = []
function spawn(i) {
  const h = idHash(i, 0), h2 = idHash(i, 7), h3 = idHash(i, 13)
  const rb = world.createRigidBody(
    RAPIER.RigidBodyDesc.dynamic()
      .setTranslation((h - 0.5) * 0.44, 2.3 + h3 * 0.12, (h2 - 0.5) * 0.44)
      .setLinearDamping(0.35).setAngularDamping(0.8).setCcdEnabled(true)
  )
  world.createCollider(RAPIER.ColliderDesc.ball(BEAD_R).setFriction(0.55).setRestitution(0.3).setDensity(1), rb)
  bodies.push(rb)
}

// Pour in small batches with settle time between, like the real drip.
const BATCH = 25
for (let n = 0; n < N; n += BATCH) {
  for (let i = 0; i < BATCH && n + i < N; i++) {
    spawn(n + i)
    for (let s = 0; s < 5; s++) world.step()
  }
  for (let s = 0; s < 360; s++) world.step()
  process.stdout.write(`\rpoured ${Math.min(n + BATCH, N)}/${N}`)
}
// Final long settle so the whole pile is calm.
for (let s = 0; s < 1200; s++) world.step()
console.log('\nsettled.')

// Keep POUR ORDER (index 0 = first poured = bottom-most; last poured rests on
// top). Pour order — not a height sort — preserves the natural mound shape at
// every partial count AND keeps each bead's slot stable as more land on top.
let escaped = 0
const kept = []
for (const b of bodies) {
  const p = b.translation()
  const q = b.rotation()
  if (p.x * p.x + p.z * p.z < 1.0 && p.y > 0) {
    kept.push({ p: [p.x, p.y, p.z], q: [q.x, q.y, q.z, q.w] })
  } else {
    escaped++
  }
}
console.log('escaped (excluded):', escaped)

const r4 = (x) => Math.round(x * 10000) / 10000
const pos = kept.map(b => b.p.map(r4))
const rot = kept.map(b => b.q.map(r4))

// Height curve every 25 beads — the pile top (incl. radius) at that count, used
// to keep the milestone lines (HomeScreen PILE_CURVE) consistent with this bake.
const curve = []
for (let c = 25; c <= pos.length; c += 25) {
  const top = pos.slice(0, c).reduce((m, p) => Math.max(m, p[1]), 0) + BEAD_R
  curve.push([c, r4(top)])
}

const out = `// AUTO-GENERATED by scripts/bake-pile.mjs — do not edit by hand.
// A real settled pile of ${pos.length} beads (rapier, BEAD_R=${BEAD_R}), sorted
// bottom→top. BeadJar3D places already-earned beads at these exact spots on load
// so the jar is identical every reload with no re-pour and no escapees.
export const PILE_POSITIONS = ${JSON.stringify(pos)}
export const PILE_ROTATIONS = ${JSON.stringify(rot)}
`
writeFileSync(new URL('../src/components/pilePositions.js', import.meta.url), out)
console.log(`wrote src/components/pilePositions.js — ${pos.length} beads`)
console.log('pile-top height curve (count, worldY):')
console.log(JSON.stringify(curve))
